plugins:
  - "prettier-plugin-tailwindcss"
  - "prettier-plugin-classnames"
  - "prettier-plugin-merge"
tabWidth: 2
useTabs: false
bracketSameLine: true
tailwindFunctions:
  - "clsx"
customFunctions:
  - "clsx"
