import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Init from "@/lib/firebase/Init";
import Navbar from "@/components/Navbar";

import "@/styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-bg color-main">
      <body className={inter.className}>
        <Init />
        <Navbar />
        <main className="h-screen">{children}</main>
      </body>
    </html>
  );
}
